### ISSUE TITLE
node_modules/.bin prefix possibly confusing?

### ISSUE THREAD

**Issue by reubengt** [emilyb7/FAC-devops-workshop#14]
Hey🙌

I'm mentoring fac20 on devops for their student projects, and thought I'd do this workshop as its been a while since I set all this up.

Was super curious why you had  `./node_modules/.bin` prefixed to all the npm scripts in package.json, as I had never seen this done before.

Did some [digging](https://docs.npmjs.com/cli/run-script) and found out that node scripts run by default in node_modules/.bin 🤯

`
In addition to the shell’s pre-existing PATH, npm run adds node_modules/.bin to the PATH provided to scripts. 
Any binaries provided by locally-installed dependencies can be used without the node_modules/.bin prefix.
`

The students are used to seeing something like:

```
"scripts": {
    "test": "tape test.js | tap-spec-emoji",
    "test:quiet": "tape test.js | tap-pessimist",
    "prettier": "prettier . --write",
    "lint": "eslint . --fix"
  }
```

and it works the same as far as I can see, and this is also covered in the [FAC npm intro](https://github.com/foundersandcoders/npm-introduction#npm-scripts)

similarly, running `./node_modules/.bin/prettier . --write` in the terminal can be replaced with `npx prettier . --write`, the students cover npx already in node week.

I have a few questions:

1) Am I missing something?😅
2) I wonder if leaving it in will prompt students to do some research and arrive at the same conclusions, in which case it'll be good learning for them.
3) A trial run to see if anyone asks questions about this bit might be a good idea? Has this workshop been delivered before?

**Comment by emilyb7** [comment]
@reubengt thank you so much for this 🤩 

It's me that's missing something. I usually use yarn rather than npm, but didn't want to introduce any other new tooling here.

I'll make the changes and include a linke to the npm intro, which is super useful :)

**Comment by reubengt** [comment]
Sounds good! The npm intro was recently updated as well, to make this clearer, because students did end up being confused by `node_modules/.bin` in the slack.

great workshop btw, I didn't know GitHub actions existed, nice to have it all built in to the repo like that👌✨
